# Generated by Django 5.2 on 2025-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dpnxbddic/image/upload/v1745587133/default_profile_us7dxw.jpg', upload_to='images/'),
        ),
    ]
