# Generated by Django 5.2 on 2025-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_us7dxw_phmfan.jpg', upload_to='images/'),
        ),
    ]
