# Generated by Django 3.2.25 on 2025-05-02 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_auto_20250501_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followed_name',
            new_name='followed',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed')},
        ),
    ]
